#!/bin/bash
# Voi6 bootstrap — turn a stock Void glibc ROOTFS into an s6-driven rootfs whose
# entire service layer is generated by mycel-compose.
#
# Runs ROOTLESS: it re-execs itself inside a user+mount namespace mapped to root
# (unshare --map-auto), so chroot + bind mounts + xbps-install work without sudo.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD="$HERE/build"
ROOTFS="$BUILD/rootfs"
TARBALL="$BUILD/void-rootfs.tar.xz"
SERVICES="$HERE/services"
SCRIPTS="$HERE/s6-linux-init/scripts"
COMPOSE="${COMPOSE:-/home/tghrl/mycel-os/mycel-compose/target/release/mycel-compose}"

BLUE='\033[0;34m'; GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'
step() { echo -e "\n${BLUE}::${NC} $1"; }
ok()   { echo -e "   ${GREEN}ok${NC} $1"; }
die()  { echo -e "   ${RED}!!${NC} $1"; exit 1; }

# ── Re-exec inside a rootless root namespace ──────────────────────────────────
if [ -z "${VOI6_NS:-}" ]; then
    command -v newuidmap >/dev/null || die "newuidmap missing (need uidmap pkg)"
    [ -x "$COMPOSE" ] || die "mycel-compose not built at $COMPOSE"
    [ -f "$TARBALL" ] || die "Void ROOTFS not found at $TARBALL"
    exec env VOI6_NS=1 unshare --map-auto --map-root-user --mount --fork \
        "${BASH_SOURCE[0]}" "$@"
fi

# Packages we add on top of the stock ROOTFS. Void already provides glibc,
# util-linux (agetty), coreutils, bash, xbps.
# eudev is already in the stock ROOTFS, so it's not listed here.
PKGS=(
    skalibs execline s6 s6-rc s6-linux-init   # the supervision suite
    dbus                                       # system bus
    seatd                                      # seat management
    dhcpcd                                     # networking
    linux                                      # kernel + (pulls dracut) initramfs
)

cleanup() {
    umount -lR "$ROOTFS/var/cache/xbps" 2>/dev/null || true
    umount -lR "$ROOTFS/dev"  2>/dev/null || true
    umount -lR "$ROOTFS/sys"  2>/dev/null || true
    umount -lR "$ROOTFS/proc" 2>/dev/null || true
}
trap cleanup EXIT

# ── 1. Fresh rootfs from the tarball ──────────────────────────────────────────
step "extracting stock Void ROOTFS..."
rm -rf "$ROOTFS"; mkdir -p "$ROOTFS"
tar -xpf "$TARBALL" -C "$ROOTFS"
ok "extracted"

# ── 2. Pseudo-filesystems + DNS for xbps inside the chroot ────────────────────
step "preparing chroot..."
mkdir -p "$ROOTFS"/{proc,sys,dev,dev/pts,run}
# Bind the host's pseudo-fs: a fresh `-t proc`/`-t sysfs` mount needs a PID
# namespace we own, which unshare --map-auto alone doesn't grant. Bind mounts of
# already-mounted filesystems are permitted with the mapped CAP_SYS_ADMIN.
mount --rbind /proc    "$ROOTFS/proc"
mount --rbind /sys     "$ROOTFS/sys"
mount --rbind /dev     "$ROOTFS/dev"
# Persist the xbps download cache across runs so a re-bootstrap doesn't re-pull
# ~750 MB. Lives on the host at build/xbps-cache, bound into the rootfs.
mkdir -p "$BUILD/xbps-cache" "$ROOTFS/var/cache/xbps"
mount --bind "$BUILD/xbps-cache" "$ROOTFS/var/cache/xbps"
cp -L /etc/resolv.conf "$ROOTFS/etc/resolv.conf"
ok "chroot ready"

# ── 3. Install the s6 stack + kernel via xbps ─────────────────────────────────
step "xbps-install: ${PKGS[*]}"
chroot "$ROOTFS" xbps-install -Suy xbps >/dev/null 2>&1 || true   # self-update first

# Void packages s6-linux-init as a HARD CONFLICT with runit-void: both claim
# PID 1. Displacing runit means actually removing it (and the base-system meta
# that pins it) before s6-linux-init will install. This is the real crux of
# putting s6 on Void — not a symlink swap. We keep the `runit` supervision
# binaries (a separate package) out of the way; nothing in Voi6 uses them.
step "removing runit-void (conflicts with s6-linux-init)..."
# Remove ONLY the meta packages that pin runit-void (the ROOTFS uses
# base-container-full; ISO/disk images use base-system), then runit-void itself.
# No -R: that would orphan-remove the meta's whole dependency closure (glibc!).
chroot "$ROOTFS" xbps-remove -y base-container-full base-system 2>/dev/null || true
chroot "$ROOTFS" xbps-remove -y runit-void \
    || die "could not remove runit-void"
ok "runit-void removed"

chroot "$ROOTFS" xbps-install -Sy "${PKGS[@]}" \
    || die "xbps-install failed"
ok "packages installed"

# Record the real udevd path — eudev's location is the one path-coupling that
# Voi6's service .toml hard-codes; fail loudly if Void moved it.
[ -x "$ROOTFS/usr/bin/udevd" ] || die "udevd not at /usr/bin/udevd — update udevd.toml"
ok "udevd verified at /usr/bin/udevd"

# ── 4. Base config ────────────────────────────────────────────────────────────
step "writing base config..."
printf 'voi6\n' > "$ROOTFS/etc/hostname"
printf '127.0.0.1\tlocalhost\n127.0.1.1\tvoi6\n::1\tlocalhost\n' > "$ROOTFS/etc/hosts"
cat > "$ROOTFS/etc/fstab" <<'EOF'
tmpfs /tmp     tmpfs nosuid,nodev,mode=1777 0 0
tmpfs /dev/shm tmpfs nosuid,nodev,mode=1777 0 0
EOF
cat > "$ROOTFS/etc/os-release" <<'EOF'
NAME="Voi6"
PRETTY_NAME="Voi6 (Void + s6)"
ID=voi6
ID_LIKE=void
EOF
# seatd's group, and a normal login user.
chroot "$ROOTFS" groupadd -rf seat 2>/dev/null || true
if ! chroot "$ROOTFS" id voi >/dev/null 2>&1; then
    chroot "$ROOTFS" useradd -m -G wheel,seat,video,input -s /bin/bash voi 2>/dev/null || true
fi
chroot "$ROOTFS" sh -c 'passwd -d root; passwd -d voi' 2>/dev/null || true
ok "base config written"

# ── 5. Weave the s6-rc tree with mycel-compose (the field test) ────────────────
step "mycel-compose -> s6-rc source tree..."
mkdir -p "$ROOTFS/etc/s6-rc"
"$COMPOSE" --services "$SERVICES" --out "$ROOTFS/etc/s6-rc/source" \
    || die "mycel-compose failed"
chroot "$ROOTFS" s6-rc-compile /etc/s6-rc/compiled /etc/s6-rc/source \
    || die "s6-rc-compile failed"
ok "s6-rc database compiled"

# ── 6. s6-linux-init as PID 1 (displace runit) ────────────────────────────────
step "installing s6-linux-init as PID 1..."
# Void's s6-linux-init package ships a skeleton /etc/s6-linux-init, but
# s6-linux-init-maker refuses to write into an existing dir. Clear it first so
# the maker generates a fresh, self-consistent config (MycelOS never hits this
# because it builds s6 from source — the dir doesn't pre-exist there).
rm -rf "$ROOTFS/etc/s6-linux-init"
chroot "$ROOTFS" s6-linux-init-maker \
    -1 -B \
    -p /usr/bin:/usr/sbin:/bin:/sbin \
    -c /etc/s6-linux-init \
    /etc/s6-linux-init \
    || die "s6-linux-init-maker failed"

install -Dm755 "$SCRIPTS/rc.init"     "$ROOTFS/etc/s6-linux-init/scripts/rc.init"
install -Dm755 "$SCRIPTS/rc.shutdown" "$ROOTFS/etc/s6-linux-init/scripts/rc.shutdown"

# /sbin/init was runit-init; point it at s6-linux-init's init (relative link).
ln -sfn ../etc/s6-linux-init/bin/init "$ROOTFS/usr/sbin/init"
ln -sfn ../etc/s6-linux-init/bin/init "$ROOTFS/usr/bin/init" 2>/dev/null || true
for cmd in halt poweroff reboot shutdown telinit; do
    [ -e "$ROOTFS/etc/s6-linux-init/bin/$cmd" ] && \
        ln -sfn "../etc/s6-linux-init/bin/$cmd" "$ROOTFS/usr/bin/$cmd"
done
ok "s6-linux-init wired; runit displaced"

cleanup
trap - EXIT
echo
ok "bootstrap complete — run build-image.sh to make the QEMU disk"
